### ISSUE TITLE
Cannot decline earlier than i'm asked...

### ISSUE THREAD

**Issue by madjor5** [jbroni/roundpieces-slackbot#1]
I'm most definitely on holiday next week - how am I to respond already now?

**Comment by jbroni** [comment]
You can't at the moment.

To do it properly, we would probably have to set up a proper database for the system. This should probably be done regardless so the bot can handle being restarted without losing state.
We could implement it without the database and just rely on the bot not dying between your response and the next meeting.

I'll prioritize it for the next release.
